### ISSUE TITLE
Tagged release?

### ISSUE THREAD

**Issue by dtzWill** [ceeac/boomerang#1]
It's awesome seeing the constant improvements you're making!

I maintain a downstream packaging of this, and just wanted to chat/ask about plans for a release? Or is it recommended to follow master?

Thanks!

**Comment by ceeac** [comment]
Hi!

Yes, for releases I recommend to follow master. I am using the [gitflow model](https://nvie.com/posts/a-successful-git-branching-model/) for branch management, so 0.4.0 will be tagged in master upon release. However, I am against a release in the near future for several reasons:

1. There are still a number of bugs that need to be fixed. Most prominently, the SPARC decoder is currently broken (Though I am not sure if it will be used much in relation to the x86 decoder)
2. When there is a release, it should imo be a somehow "official" one. I have not yet decided on how to approach this matter, as upstream seems to be unmaintained last time I checked, and also because I wanted to some more refactoring/documentation/unit testing work first.

**Comment by dtzWill** [comment]
Okay, that all sounds great! Thanks for the thoughtful response and project management, I'll keep following master for the time being and thanks for your continued work!

**Comment by ceeac** [comment]
@dtzWill just a heads-up: Boomerang is now maintained at BoomerangDecompiler/boomerang. Also, there is going to be a release soon-ish (most likely this year).

**Comment by dtzWill** [comment]
Great!

And thank you for letting me know, I'll update accordingly and keep
an eye on development over there!
